FROM cypress/base as deps

WORKDIR /usr/app
COPY package.json package-lock.json ./
RUN npm ci

FROM cypress/base as run

WORKDIR /usr/app
COPY --from=deps /usr/app/ /usr/app/
COPY . .

CMD [ "npm", "run", "test:all" ]
