FROM cypress/included:cypress-12.12.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1 as deps

WORKDIR /usr/app
COPY package.json package-lock.json ./
RUN npm ci

FROM cypress/included:cypress-12.12.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1 as run

WORKDIR /usr/app
COPY --from=deps /usr/app/ /usr/app/
COPY . .

CMD [ "npm", "run", "test:all:ci" ]
