FROM node:18-alpine as deps

WORKDIR /usr/app
COPY package.json package-lock.json ./
RUN npm ci


FROM node:18-alpine as build

WORKDIR /usr/app
COPY --from=deps /usr/app/ /usr/app/
COPY . .
RUN npm run build

FROM node:18-alpine as run

WORKDIR /usr/app
COPY --from=build /usr/app/ /usr/app/
EXPOSE 3000
# Run container as non-root (unprivileged) user
# The node user is provided in the Node.js Alpine base image
USER node

CMD [ "npm", "run", "start:test" ]
